[workspace]
resolver = "3"
members = [
    "Async_Programming",
    "Collections",
    "Cryptogrphy_Encryption",
    "Databases",
    "DataStructures",
    "DesignPatterns",
    "Files_Folders_Directories",
    "GRpc",
    "Json",
    "Logging",
    "Memory",
    "Multithreading",
    "Networking",
    "Performance",
    "Protobuf",
    "Serialization",
    "StdLibrary",
    "Testing",
    "Tests_and_Experiments",
    "Web_Framework",
    "ZeroMQ",
    "ZeroMQ_ProtoBuff"
]
