[package]
name = "Multithreading"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["time", "rt", "rt-multi-thread", "macros", "sync"] }
flume = "0.11.1"
chrono = "0.4.41"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
tracing = "0.1.41"
