[package]
name = "Logging"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
simple_logger = "5.0.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["json", "env-filter"] }
tracing-appender = "0.2.3"
