version: '3.9'

services:

    clickhouse:

        image: clickhouse/clickhouse-server:latest
        container_name: clickhouse-server
        ports:
            - "8123:8123" # HTTP interface
            - "9000:9000" # Native client interface
            - "9009:9009" # Secure native client interface (if enabled)

        volumes:
          - /home/andtokm/DiskS/Temp/docker/clickhouse/data:/var/lib/clickhouse             # Persistent data storage
          - /home/andtokm/DiskS/Temp/docker/clickhouse/logs:/var/log/clickhouse-server      # Persistent logs
          - /home/andtokm/DiskS/Temp/docker/clickhouse/config:/etc/clickhouse-server/conf.d # Custom configuration

        environment:
            # Optional: Set ClickHouse user and password for initial setup
            CLICKHOUSE_USER: myuser
            CLICKHOUSE_PASSWORD: mypassword

        ulimits:
            nofile:
                soft: 262144
                hard: 262144

        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8123/ping"]
            interval: 30s
            timeout:  10s
            retries:  3

        # networks:
        #     - clickhouse-net
        network_mode: "host"


    mysql_db_service:

        hostname: mysql_database
        restart: always
        container_name: mysql_database

        image: mysql
        # image: mysql:latest

        volumes:
            - /home/andtokm/DiskS/Temp/docker/mysql:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_database
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=qwerty12345

        ports:
            - 3306:3306/tcp
            - 33060:33060/tcp

        network_mode: "host"


networks:
    #clickhouse-net:
    #    driver: bridge
    host:
        name: host
        external: true