[package]
name = "Protobuf"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
prost-build = "0.14.1"
protobuf-codegen-pure = "3.0.0-alpha.2"

[build-dependencies]
prost-build = "0.14.1"